name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
     - uses: actions/checkout@v2
       with: 
         submodules: 'true'

     - if: matrix.os == 'ubuntu-latest'
       name: CMake Generate (Linux)
       run: CXX=g++-9 CC=gcc-9 cmake -DOUT_DIRECTORY=TRUE -DBUILD_ZRATOOL=TRUE -DBUILD_SHARED_LIBS=TRUE -B build .

     - if: matrix.os != 'ubuntu-latest'
       name: CMake Generate
       run: cmake -DOUT_DIRECTORY=TRUE -DBUILD_ZRATOOL=TRUE -DBUILD_SHARED_LIBS=TRUE -B build .
     
     - name: CMake Build
       run: cmake --build build --config Release
     
     - name: Upload Development Package
       uses: actions/upload-artifact@v2
       with:
         name: libzra-${{matrix.os}}
         path: out
